accent = "#ffbe55"
cursor = "#f7dd9b"
foreground = "#fff3cf"
background = "#292025"
selection_foreground = "#fff3cf"
selection_background = "#ffbe55"

color0 = "#292025"
color1 = "#ff8c68"
color2 = "#f0e65a"
color3 = "#a4a900"
color4 = "#ffbe55"
color5 = "#c7f3ff"
color6 = "#c5a0b6"
color7 = "#fff3cf"
color8 = "#834f36"
color9 = "#ff8c68"
color10 = "#f0e65a"
color11 = "#a4a900"
color12 = "#ffbe55"
color13 = "#c7f3ff"
color14 = "#c5a0b6"
color15 = "#e88f37"
